# Generated by Django 5.2.7 on 2025-10-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoprov', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('upc1', models.CharField(max_length=100)),
                ('upc2', models.CharField(max_length=100)),
                ('mult1', models.IntegerField(default=0)),
                ('mult2', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
