# Generated by Django 5.2.7 on 2025-11-16 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_unidadmedida_product_unidad_medida1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='codigoprov',
            field=models.ForeignKey(blank=True, db_column='codigoprov', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.proveedor'),
        ),
    ]
