# Generated by Django 5.2.7 on 2025-11-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_codigoprov'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
