# Generated by Django 4.2.5 on 2025-11-19 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('folio', models.CharField(help_text='Formato: xx-xxxxx', max_length=8)),
                ('productos', models.CharField(max_length=255)),
                ('estatus', models.BooleanField(default=False, help_text='True = Enviado, False = No enviado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='main.cliente')),
            ],
        ),
    ]
