# Generated by Django 4.2.5 on 2025-11-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
