# Generated by Django 4.2.5 on 2025-11-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_pedido_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.CharField(default='DD/MM/YYYY', max_length=10),
        ),
    ]
