# Generated by Django 4.2.5 on 2025-11-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_pedido_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha',
        ),
        migrations.AddField(
            model_name='pedido',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
