# Generated by Django 4.2.5 on 2025-11-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_pedido_fecha_pedido_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
