# Generated by Django 4.2.5 on 2025-11-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_categoria_product_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='folio',
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
