# Generated by Django 4.2.5 on 2026-01-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_pedido_folio_pedido_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
